# Generated by Django 2.0.1 on 2020-05-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scoreboard_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores',
            name='Id',
            field=models.BigIntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='scores',
            name='Score',
            field=models.BigIntegerField(),
        ),
    ]
